"""
Django settings for managerPanel project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!lz1ztarurm_u8(^k5lol_fp^5_59ap^w03lh!z-k^)3k_(svs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']


CORS_ALLOWED_ORIGINS = [
    "http://uzradyab.ir",
    "https://app.uzradyab.ir",
    "http://app.uzradyab.ir",
    "http://localhost:3000",  # For development on localhost
     "http://localhost:5173",  # For development on localhost
     "https://sipaad.exirfirm.com"
]

CSRF_TRUSTED_ORIGINS = [
    'https://app.uzradyab.ir',
    'https://pay.uzradyab.ir',  # Add if you have requests originating from here as well
    'http://localhost:3000',     # Add localhost for development
    "http://localhost:5173",  # For development on localhost
    "https://sipaad.exirfirm.com"
]

CSRF_COOKIE_SECURE = True  # Ensures CSRF cookies are only sent over HTTPS
CSRF_COOKIE_SAMESITE = 'None'  # Allows the CSRF cookie to be sent cross-site
SESSION_COOKIE_SECURE = True  # Ensures session cookies are only sent over HTTPS


# Application definition
TOKEN_EXPIRATION_TIME = None
INSTALLED_APPS = [
    'main',
    'rest_framework',
    'rest_framework.authtoken',
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jalali_date',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'managerPanel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'managerPanel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

# import locale
# locale.setlocale(locale.LC_ALL, "Persian_Iran.UTF-8")

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = '/opt/traccar/web/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SANDBOX MODE

MERCHANT = "0a36c5ed-3774-4631-ada6-39b885d738a4"

SANDBOX = False



# local DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'uzradyab',
#         'USER': 'postgres',
#         'PASSWORD': '3h4wfv7ue9re',
#         'HOST': '62.60.132.92',  # Or your database host
#         'PORT': '5432',       # Or your database port
#     },
#     'uzradyab': {
#         'ENGINE': 'django.db.backends.postgresql',  # secondary database engine
#         'NAME': 'traccar',
#         'USER': 'postgres',
#         'PASSWORD': '3h4wfv7ue9re',
#         'HOST': '62.60.132.92',
#         'PORT': '5432',
#     }
# }


# server DB 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'uzradyab',
        'USER': 'postgres',
        'PASSWORD': '3h4wfv7ue9re',
        'HOST': '127.0.0.1',  # Or your database host
        'PORT': '5432',       # Or your database port
    },
    'uzradyab': {
        'ENGINE': 'django.db.backends.postgresql',  # secondary database engine
        'NAME': 'traccar',
        'USER': 'postgres',
        'PASSWORD': '3h4wfv7ue9re',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
