# Generated by Django 5.0.4 on 2025-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='traccar_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
