# Generated by Django 5.0.4 on 2025-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='traccar_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
