# Generated by Django 5.0.4 on 2025-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('support', 'Support'), ('admin', 'Admin')], default='customer', help_text='Designates the type of user account.', max_length=20),
        ),
    ]
