# Generated by Django 5.0.4 on 2024-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=100, verbose_name='شناسه یکتا')),
                ('name', models.CharField(default='', max_length=100, verbose_name='نام')),
                ('id_number', models.CharField(default='', max_length=100, verbose_name='شناسه')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='شماره تلفن')),
                ('period', models.CharField(default='', max_length=20, verbose_name='مدت زمان')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='مقدار')),
                ('payment_code', models.CharField(default='', max_length=100, verbose_name='کد پرداخت')),
                ('verification_code', models.CharField(default='', max_length=100, verbose_name='کد تایید')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='', max_length=100, verbose_name='دوره')),
                ('description', models.CharField(default='', max_length=100, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, default=None, max_digits=20, null=True, verbose_name='هزینه (تومان)')),
                ('phone', models.DecimalField(decimal_places=0, default=None, max_digits=11, null=True, verbose_name='تلفن')),
                ('duration_months', models.IntegerField(default=1, verbose_name='مدت اعتبار (ماه)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
