# Generated by Django 5.0.4 on 2024-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='', max_length=100, verbose_name='دوره')),
                ('description', models.CharField(default='', max_length=100, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, default=None, max_digits=20, null=True, verbose_name='هزینه (تومان)')),
                ('phone', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=11, null=True, verbose_name='تلفن برای درگاه پرداخت')),
                ('duration_days', models.IntegerField(default=1, verbose_name='مدت اعتبار (روز)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'شارژ حساب',
                'verbose_name_plural': 'تنظیمات شارژ حساب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=100, verbose_name='شناسه یکتا')),
                ('name', models.CharField(default='', max_length=100, verbose_name='نام')),
                ('id_number', models.CharField(default='', max_length=100, verbose_name='شناسه')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='شماره تلفن')),
                ('period', models.CharField(default='', max_length=100, verbose_name='مدت زمان')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='مقدار پرداخت')),
                ('payment_code', models.CharField(default='', max_length=100, verbose_name='کد پرداخت')),
                ('verification_code', models.CharField(default='', max_length=100, verbose_name='کد تایید')),
                ('status', models.CharField(default='', max_length=100, verbose_name='وضعیت پرداخت')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('background_color', models.CharField(max_length=20)),
            ],
        ),
    ]
