# Generated by Django 5.0.4 on 2024-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='', max_length=100, verbose_name='دوره')),
                ('description', models.CharField(default='', max_length=100, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, default=None, max_digits=20, null=True, verbose_name='هزینه (تومان)')),
                ('phone', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=11, null=True, verbose_name='تلفن برای درگاه پرداخت')),
                ('duration_months', models.IntegerField(default=1, verbose_name='مدت اعتبار (ماه)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'شارژ حساب',
                'verbose_name_plural': 'تنظیمات شارژ حساب\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
