# Generated by Django 5.0.4 on 2024-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payment_account_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcharge',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=20, null=True, verbose_name='هزینه (ریال)'),
        ),
    ]
