# Generated by Django 5.0.4 on 2025-08-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_accountcharge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='imei',
            field=models.CharField(default='', max_length=50, verbose_name='سریال دستگاه'),
            preserve_default=False,
        ),
    ]
