# Generated by Django 5.0.4 on 2024-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_status_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(default='', max_length=100, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='شماره تلفن'),
        ),
    ]
