# Generated by Django 5.0.4 on 2025-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سریال دستگاه'),
        ),
    ]
