# Generated by Django 5.0.4 on 2025-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_payment_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='device_id_number',
            field=models.CharField(default='', max_length=100, verbose_name='شناسه دستگاه'),
        ),
    ]
