# Generated by Django 5.0.4 on 2025-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_payment_id_number_payment_device_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcharge',
            name='credit_cost',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
