# Generated by Django 5.0.4 on 2025-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit', 'اعتبار'), ('gateway', 'درگاه پرداخت')], default='gateway', max_length=10, verbose_name='روش پرداخت'),
        ),
    ]
