# Generated by Django 5.0.4 on 2025-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه یکتا'),
        ),
    ]
