# Generated by Django 5.0.4 on 2025-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_payment_name_alter_payment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('credit', 'اعتبار'), ('gateway', 'درگاه پرداخت')], max_length=10, null=True, verbose_name='روش پرداخت'),
        ),
    ]
