# Generated by Django 5.0.4 on 2025-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='device_id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دستگاه'),
        ),
    ]
