# Generated by Django 5.0.4 on 2025-07-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('uniqueid', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('expirationtime', models.DateTimeField()),
                ('user_emails', models.JSONField(default=list)),
                ('user_phones', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'expired_devices',
                'ordering': ['-expirationtime'],
                'unique_together': {('device_id', 'expirationtime')},
            },
        ),
    ]
