# Generated by Django 5.0.4 on 2025-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzradyabHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireddevice',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات اضافی در مورد دستگاه'),
        ),
        migrations.AlterField(
            model_name='expireddevice',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('notified', 'بررسی شده'), ('renewed', 'تکمیل شده')], default='pending', max_length=20),
        ),
    ]
