# Generated by Django 5.0.4 on 2025-08-12 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traccar_user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('administrator', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('expiration_time', models.DateTimeField()),
                ('device_limit', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Expired User',
                'verbose_name_plural': 'Expired Users',
                'ordering': ['-detected_at'],
            },
        ),
    ]
