# Generated by Django 5.0.4 on 2025-08-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traccar_calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireduser',
            name='sms_30_days_after_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expireduser',
            name='sms_3_days_after_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expireduser',
            name='sms_3_days_before_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expireduser',
            name='sms_expire_day_sent',
            field=models.BooleanField(default=False),
        ),
    ]
