# Generated by Django 5.0.4 on 2025-09-03 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traccar_calls', '0002_expireduser_sms_30_days_after_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('administrator', models.BooleanField(default=False)),
                ('user_disabled', models.BooleanField(default=False)),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_uniqueid', models.CharField(blank=True, max_length=200)),
                ('device_phone', models.CharField(blank=True, max_length=20)),
                ('device_disabled', models.BooleanField(default=False)),
                ('device_status', models.CharField(blank=True, max_length=50)),
                ('expiration_time', models.DateTimeField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sms_3_days_before_sent', models.BooleanField(default=False)),
                ('sms_expire_day_sent', models.BooleanField(default=False)),
                ('sms_3_days_after_sent', models.BooleanField(default=False)),
                ('sms_30_days_after_sent', models.BooleanField(default=False)),
                ('sms_3_days_before_date', models.DateTimeField(blank=True, null=True)),
                ('sms_expire_day_date', models.DateTimeField(blank=True, null=True)),
                ('sms_3_days_after_date', models.DateTimeField(blank=True, null=True)),
                ('sms_30_days_after_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expiration_time'],
                'unique_together': {('user_id', 'device_id')},
            },
        ),
        migrations.DeleteModel(
            name='ExpiredUser',
        ),
    ]
